repos:
  - repo: local
    hooks:
      - id: check_tooling_version
        name: Check tooling version
        entry: python3 pre-commit.py
        language: python
        always_run: true
        fail_fast: true
        verbose: true